# Generated by Django 4.0.4 on 2024-03-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('c_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('u_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('availability', models.BooleanField(default=True)),
                ('in_use_of', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.companies')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('u_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
            ],
        ),
        migrations.CreateModel(
            name='device_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_time', models.DateTimeField(auto_now_add=True)),
                ('out_condition', models.CharField(default='Good', max_length=50)),
                ('return_time', models.DateTimeField(auto_now=True)),
                ('return_condition', models.CharField(default='Good', max_length=50)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.device')),
                ('used_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employee')),
            ],
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='company_wise_device'),
        ),
    ]
